### ISSUE TITLE
Troubleshooting `tmp-postgres` when using `haskell-ci`

### ISSUE THREAD

**Issue by NicolasT** [jfischoff/tmp-postgres#277]
Some codebase I've been working on uses `tmp-postgres` in its test-suite (great tool, by the way, thank you for publishing it!). This works fine on my Fedora workstation, using PostgreSQL 14.3.

I wanted to add CI to the project, using [haskell-ci](https://github.com/haskell-CI/haskell-ci), as I usually do. On GitHub Actions, this runs tests in Ubuntu-based containers, so I needed to make some modifications to ensure `initdb` is in `$PATH`. I did so using a patch applied to what's generated by `haskell-ci`. The resulting workflow file is [here](https://github.com/NicolasT/hedgehog-stateful-demo/blob/0bc83cccce851784f3242748f9ce66d528c40bd1/.github/workflows/haskell-ci.yml), the patch itself (applied by `haskell-ci`) is [here](https://github.com/NicolasT/hedgehog-stateful-demo/blob/0bc83cccce851784f3242748f9ce66d528c40bd1/.github/workflows/haskell-ci-postgresql-path.patch).

When the workflow runs, `initdb` seems to be in `$PATH` as intended, see the two invocations of `which` [here](https://github.com/NicolasT/hedgehog-stateful-demo/actions/runs/3928998888/jobs/6717268127#step:6:19) and [here](https://github.com/NicolasT/hedgehog-stateful-demo/actions/runs/3928998888/jobs/6717268127#step:22:21):

<details>
  <summary>which initdb</summary>

```
Run which initdb
  which initdb
  shell: sh -e {0}
  env:
    LANG: C.UTF-8
    CABAL_DIR: /github/home/.cabal
    CABAL_CONFIG: /github/home/.cabal/config
    HC: /github/home/.ghcup/bin/ghc-9.4.4
    HCPKG: /github/home/.ghcup/bin/ghc-pkg-9.4.4
    HADDOCK: /github/home/.ghcup/bin/haddock-9.4.4
    CABAL: /github/home/.ghcup/bin/cabal-3.6.2.0 -vnormal+nowrap
    HCNUMVER: 90404
    ARG_TESTS: --enable-tests
    ARG_BENCH: --enable-benchmarks
    HEADHACKAGE: false
    ARG_COMPILER: --ghc --with-compiler=/github/home/.ghcup/bin/ghc-9.4.4
    GHCJSARITH: 0
/usr/lib/postgresql/14/bin/initdb
```
</details>

However, when running the test-suite, things fail ([source](https://github.com/NicolasT/hedgehog-stateful-demo/actions/runs/3928998888/jobs/6717268127#step:22:211)):

```
InitDbFailed {startErrorStdOut = "", startErrorStdErr = "", startErrorExitCode = ExitFailure 1}
```

I adapted the code to use `withConfig verboseConfig`, and got the following ([source](https://github.com/NicolasT/hedgehog-stateful-demo/actions/runs/3928998888/jobs/6717268127#step:22:34)):

<details>
  <summary>verboseConfig output</summary>

```
StartPlan:
completePlanInitDb:
  completeProcessConfigEnvVars:
    hedgehog_stateful_demo_datadir: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0/.
    PKGDIR_hedgehog_stateful_demo: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0
    GITHUB_STATE: /__w/_temp/_runner_file_commands/save_state_6319ad94-72d6-4d78-8183-232142f107bf
    ARG_TESTS: --enable-tests
    CI: true
    HOSTNAME: 340816af5edc
    HC: /github/home/.ghcup/bin/ghc-9.4.4
    GITHUB_ENV: /__w/_temp/_runner_file_commands/set_env_6319ad94-72d6-4d78-8183-232142f107bf
    HOME: /github/home
    ARG_COMPILER: --ghc --with-compiler=/github/home/.ghcup/bin/ghc-9.4.4
    CABAL: /github/home/.ghcup/bin/cabal-3.6.2.0 -vnormal+nowrap
    GHCJSARITH: 0
    GITHUB_EVENT_PATH: /github/workflow/event.json
    RUNNER_TEMP: /__w/_temp
    HADDOCK: /github/home/.ghcup/bin/haddock-9.4.4
    GITHUB_REPOSITORY_OWNER: NicolasT
    GITHUB_RETENTION_DAYS: 90
    GITHUB_REPOSITORY_OWNER_ID: 102605
    GITHUB_HEAD_REF: 
    GITHUB_GRAPHQL_URL: https://api.github.com/graphql
    CABAL_DIR: /github/home/.cabal
    HCNUMVER: 90404
    GITHUB_API_URL: https://api.github.com/
    RUNNER_OS: Linux
    GITHUB_WORKFLOW: Haskell-CI
    GITHUB_RUN_ID: 3928998888
    GITHUB_BASE_REF: 
    GITHUB_REF_TYPE: branch
    GITHUB_WORKFLOW_SHA: 0bc83cccce851784f3242748f9ce66d528c40bd1
    GITHUB_WORKFLOW_REF: NicolasT/hedgehog-stateful-demo/.github/workflows/haskell-ci.yml@refs/heads/ci
    GITHUB_ACTION_REPOSITORY: 
    PATH: /usr/lib/postgresql/14/bin:/github/home/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    RUNNER_TOOL_CACHE: /__t
    GITHUB_RUN_NUMBER: 7
    GITHUB_TRIGGERING_ACTOR: NicolasT
    GITHUB_ACTION: __run_18
    RUNNER_ARCH: X64
    LANG: C.UTF-8
    GITHUB_REPOSITORY: NicolasT/hedgehog-stateful-demo
    GITHUB_REF_NAME: ci
    RUNNER_NAME: Hosted Agent
    GITHUB_ACTION_REF: 
    GITHUB_ACTIONS: true
    GITHUB_REPOSITORY_ID: 589012755
    ARG_BENCH: --enable-benchmarks
    GITHUB_REF_PROTECTED: false
    GITHUB_JOB: linux
    GITHUB_WORKSPACE: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo
    GITHUB_SHA: 0bc83cccce851784f3242748f9ce66d528c40bd1
    GITHUB_RUN_ATTEMPT: 1
    GITHUB_REF: refs/heads/ci
    GITHUB_ACTOR: NicolasT
    CABAL_CONFIG: /github/home/.cabal/config
    GITHUB_ACTOR_ID: 102605
    GITHUB_PATH: /__w/_temp/_runner_file_commands/add_path_6319ad94-72d6-4d78-8183-232142f107bf
    RUNNER_WORKSPACE: /__w/hedgehog-stateful-demo
    PWD: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo
    GITHUB_EVENT_NAME: push
    GITHUB_SERVER_URL: https://github.com/
    GITHUB_OUTPUT: /__w/_temp/_runner_file_commands/set_output_6319ad94-72d6-4d78-8183-232142f107bf
    HCPKG: /github/home/.ghcup/bin/ghc-pkg-9.4.4
    HEADHACKAGE: false
    GITHUB_STEP_SUMMARY: /__w/_temp/_runner_file_commands/step_summary_6319ad94-72d6-4d78-8183-232142f107bf
    HASKELL_DIST_DIR: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/dist-newstyle/build/x86_64-linux/ghc-9.4.4/hedgehog-stateful-demo-0.1.0.0/t/hedgehog-stateful-demo-test
    hedgehog_stateful_demo_datadir: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0/.
  completeProcessConfigCmdLine:
  --no-sync --pgdata=/tmp/tmp-postgres-data-71cdd1c2f7cc4009
  completeProcessConfigStdIn: HANDLE
  completeProcessConfigStdOut: HANDLE
  completeProcessConfigStdErr: HANDLE
completePlanCopy:   
completePlanCreateDb:   
completePlanPostgres:
  completePostgresPlanProcessConfig:
    completeProcessConfigEnvVars:
      hedgehog_stateful_demo_datadir: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0/.
      PKGDIR_hedgehog_stateful_demo: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0
      GITHUB_STATE: /__w/_temp/_runner_file_commands/save_state_6319ad94-72d6-4d78-8183-232142f107bf
      ARG_TESTS: --enable-tests
      CI: true
      HOSTNAME: 340816af5edc
      HC: /github/home/.ghcup/bin/ghc-9.4.4
      GITHUB_ENV: /__w/_temp/_runner_file_commands/set_env_6319ad94-72d6-4d78-8183-232142f107bf
      HOME: /github/home
      ARG_COMPILER: --ghc --with-compiler=/github/home/.ghcup/bin/ghc-9.4.4
      CABAL: /github/home/.ghcup/bin/cabal-3.6.2.0 -vnormal+nowrap
      GHCJSARITH: 0
      GITHUB_EVENT_PATH: /github/workflow/event.json
      RUNNER_TEMP: /__w/_temp
      HADDOCK: /github/home/.ghcup/bin/haddock-9.4.4
      GITHUB_REPOSITORY_OWNER: NicolasT
      GITHUB_RETENTION_DAYS: 90
      GITHUB_REPOSITORY_OWNER_ID: 102605
      GITHUB_HEAD_REF: 
      GITHUB_GRAPHQL_URL: https://api.github.com/graphql
      CABAL_DIR: /github/home/.cabal
      HCNUMVER: 90404
      GITHUB_API_URL: https://api.github.com/
      RUNNER_OS: Linux
      GITHUB_WORKFLOW: Haskell-CI
      GITHUB_RUN_ID: 3928998888
      GITHUB_BASE_REF: 
      GITHUB_REF_TYPE: branch
      GITHUB_WORKFLOW_SHA: 0bc83cccce851784f3242748f9ce66d528c40bd1
      GITHUB_WORKFLOW_REF: NicolasT/hedgehog-stateful-demo/.github/workflows/haskell-ci.yml@refs/heads/ci
      GITHUB_ACTION_REPOSITORY: 
      PATH: /usr/lib/postgresql/14/bin:/github/home/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      RUNNER_TOOL_CACHE: /__t
      GITHUB_RUN_NUMBER: 7
      GITHUB_TRIGGERING_ACTOR: NicolasT
      GITHUB_ACTION: __run_18
      RUNNER_ARCH: X64
      LANG: C.UTF-8
      GITHUB_REPOSITORY: NicolasT/hedgehog-stateful-demo
      GITHUB_REF_NAME: ci
      RUNNER_NAME: Hosted Agent
      GITHUB_ACTION_REF: 
      GITHUB_ACTIONS: true
      GITHUB_REPOSITORY_ID: 589012755
      ARG_BENCH: --enable-benchmarks
      GITHUB_REF_PROTECTED: false
      GITHUB_JOB: linux
      GITHUB_WORKSPACE: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo
      GITHUB_SHA: 0bc83cccce851784f3242748f9ce66d528c40bd1
      GITHUB_RUN_ATTEMPT: 1
      GITHUB_REF: refs/heads/ci
      GITHUB_ACTOR: NicolasT
      CABAL_CONFIG: /github/home/.cabal/config
      GITHUB_ACTOR_ID: 102605
      GITHUB_PATH: /__w/_temp/_runner_file_commands/add_path_6319ad94-72d6-4d78-8183-232142f107bf
      RUNNER_WORKSPACE: /__w/hedgehog-stateful-demo
      PWD: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo
      GITHUB_EVENT_NAME: push
      GITHUB_SERVER_URL: https://github.com/
      GITHUB_OUTPUT: /__w/_temp/_runner_file_commands/set_output_6319ad94-72d6-4d78-8183-232142f107bf
      HCPKG: /github/home/.ghcup/bin/ghc-pkg-9.4.4
      HEADHACKAGE: false
      GITHUB_STEP_SUMMARY: /__w/_temp/_runner_file_commands/step_summary_6319ad94-72d6-4d78-8183-232142f107bf
      HASKELL_DIST_DIR: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/dist-newstyle/build/x86_64-linux/ghc-9.4.4/hedgehog-stateful-demo-0.1.0.0/t/hedgehog-stateful-demo-test
      hedgehog_stateful_demo_datadir: /__w/hedgehog-stateful-demo/hedgehog-stateful-demo/unpacked/hedgehog-stateful-demo-0.1.0.0/.
    completeProcessConfigCmdLine:
    -D/tmp/tmp-postgres-data-71cdd1c2f7cc4009 -p55355
    completeProcessConfigStdIn: HANDLE
    completeProcessConfigStdOut: HANDLE
    completeProcessConfigStdErr: HANDLE
  completePostgresPlanClientOptions: host=/tmp/tmp-postgres-socket-6512f389fcd8c2f0 dbname=postgres port=55355
completePlanConfig:
  archive_mode=off
  client_min_messages=WARNING
  commit_delay=100000
  fsync=off
  full_page_writes=off
  lc_messages='C'
  listen_addresses='127.0.0.1,::1'
  log_autovacuum_min_duration=0
  log_checkpoints=on
  log_connections=on
  log_disconnections=on
  log_error_verbosity=default
  log_line_prefix='%t [%p]: '
  log_lock_waits=on
  log_min_duration_statement=0
  log_min_error_statement=WARNING
  log_min_messages=WARNING
  log_statement=none
  log_temp_files=0
  max_wal_senders=0
  shared_buffers=12MB
  synchronous_commit=off
  track_io_timing=on
  unix_socket_directories='/tmp/tmp-postgres-socket-6512f389fcd8c2f0'
  wal_level=minimal
  
completePlanDataDirectory: /tmp/tmp-postgres-data-71cdd1c2f7cc4009
```
</details>

This doesn't make me much wiser... Any pointers at how I could debug this further? Thanks in advance!
